### PR TITLE
fix auto_config and profile based configuration generation

### LINKED ISSUE #430: erlcloud_aws:auto_config seems broken in 2.2.13 compring to 2.2.12
```erlang
rp(catch erlcloud_aws:auto_config())
3> .
{'EXIT',{{aws_error,{http_error,403,"Forbidden",
                                <<"<ErrorResponse xmlns=\"https://sts.amazonaws.com/doc/2011-06-15/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>SignatureDoesNotMatch</Code>\n    <Message>Credential should be scoped to a valid region, not 'us-west-2'. </Message>\n  </Error>\n  <RequestId>3f0400f4-881f-11e7-8486-99a2c3257ccd</RequestId>\n</ErrorResponse>\n">>}},
         [{erlcloud_sts,sts_query,4,
                        [{file,"/Users/ebob/Desktop/Code/search/search/_build/default/lib/erlcloud/src/erlcloud_sts.erl"},
                         {line,141}]},
          {erlcloud_sts,assume_role,5,
                        [{file,"/Users/ebob/Desktop/Code/search/search/_build/default/lib/erlcloud/src/erlcloud_sts.erl"},
                         {line,43}]},
          {erlcloud_aws,profiles_assume,4,
                        [{file,"/Users/ebob/Desktop/Code/search/search/_build/default/lib/erlcloud/src/erlcloud_aws.erl"},
                         {line,1215}]},
          {erlcloud_aws,profiles_recurse,5,
                        [{file,"/Users/ebob/Desktop/Code/search/search/_build/default/lib/erlcloud/src/erlcloud_aws.erl"},
                         {line,1178}]},
          {erlcloud_aws,profile,2,
                        [{file,"/Users/ebob/Desktop/Code/search/search/_build/default/lib/erlcloud/src/erlcloud_aws.erl"},
                         {line,1109}]},
          {erlcloud_aws,auto_config_profile,1,
                        [{file,"/Users/ebob/Desktop/Code/search/search/_build/default/lib/erlcloud/src/erlcloud_aws.erl"},
                         {line,427}]},
          {erlcloud_aws,auto_config,1,
                        [{file,"/Users/ebob/Desktop/Code/search/search/_build/default/lib/erlcloud/src/erlcloud_aws.erl"},
                         {line,421}]},
          {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},
          {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,431}]},
          {erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,878}]},
          {shell,local_func,7,[{file,"shell.erl"},{line,1003}]},
          {erl_eval,local_func,6,[{file,"erl_eval.erl"},{line,562}]},
          {shell,exprs,7,[{file,"shell.erl"},{line,686}]},
          {shell,eval_exprs,7,[{file,"shell.erl"},{line,641}]},
          {shell,eval_loop,3,[{file,"shell.erl"},{line,626}]}]}}
```

### PR DESCRIPTION
**Pull request by motobob**
fixes #430 introduced by #428 / #423

in sing section - follow the same order in region selection as in config generation.

verified locally with OS env `"AWS_REGION"`, application env `aws_region`.
pending verifications in EC2, ECS, ~~lambda~~ deploys.

@kkuzmin please review

### CODE REVIEW

File: src/erlcloud_aws.erl [hunk 1]
```diff
@@ -146,7 +146,10 @@ aws_region_from_host(Host) ->
         [_, Value, _, _ | _Rest] ->
             Value;
         _ ->
-            application:get_env(erlcloud, aws_region, "us-east-1")
+            case default_config_get("AWS_REGION", aws_region) of
```
Comment (kkuzmin) [inline src/erlcloud_aws.erl]: I think it it worth adding `default_config_get/3` which returns default value and have just one line here
```
default_config_get("AWS_REGION", aws_region, "us-east-1")
```

**Comment by kkuzmin** [comment]
+1 in general. Just one minor refactoring comment.
